name       : yarn
version    : 1.5.1
release    : 38
source     :
    - https://github.com/yarnpkg/yarn/archive/v1.5.1.tar.gz : 46c0b55084fd4d95b363cc50e374ec1c65a2e5a882c405f21ea7611cafa049bf
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    cp -R bin lib node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn
