name       : yarn
version    : 0.24.5
release    : 26
source     :
    - https://github.com/yarnpkg/yarn/archive/v0.24.5.tar.gz : 8775c8c63314a69276de22497652fa5ee89cf392ba3c1de05b5947a10377f7ea
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    cp -R bin lib lib-legacy node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn

