name       : yarn
version    : 1.19.1
release    : 52
source     :
    - https://github.com/yarnpkg/yarn/archive/v1.19.1.tar.gz : 49f8ca1ee041af255fb999b02b3f8f7ad975212d55629fbab948771a8dd548f4
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    export yarnModules="/usr/lib/node_modules/yarn/node_modules/"
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    # Pre-copy fix for node_modules/.bin/sshpk-* broken symbolic link
    rm node_modules/.bin/sshpk-*
    # Copy
    cp -R bin lib node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn
    # Post-copy fix
    for f in sshpk-conv sshpk-sign sshpk-verify; do
        ln -s ${yarnModules}sshpk/bin/${f} $installdir/${yarnModules}.bin/${f}
    done
