name       : yarn
version    : 0.27.5
release    : 29
source     :
    - https://github.com/yarnpkg/yarn/archive/v0.27.5.tar.gz : 3b2ca8bf155e6157382e4f99ec9d84a53821344b475ea1cda486531372977bf4
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
setup: |
    %patch -p1 < $pkgfiles/0001-Do-not-use-usr-local-share-as-home-under-fakeroot.patch
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    cp -R bin lib lib-legacy node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn

