name       : yarn
version    : 1.13.0
release    : 49
source     :
    - https://github.com/yarnpkg/yarn/archive/v1.13.0.tar.gz : 3bb516636ff6bf88fb1fd0423403526e8c56695b3d9ac810f0be1ff4c9fd74c4
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    export yarnModules="/usr/lib/node_modules/yarn/node_modules/"
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    # Pre-copy fix for node_modules/.bin/sshpk-* broken symbolic link
    rm node_modules/.bin/sshpk-*
    # Copy
    cp -R bin lib node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn
    # Post-copy fix
    for f in sshpk-conv sshpk-sign sshpk-verify; do
        ln -s ${yarnModules}sshpk/bin/${f} $installdir/${yarnModules}.bin/${f}
    done
