name       : yarn
version    : 1.2.0
release    : 32
source     :
    - https://github.com/yarnpkg/yarn/archive/v1.2.0.tar.gz : 87901ab0db697a1587e7a3053812b589b1202b409d9e29dcd776400ed7649ceb
license    : BSD-2-Clause
component  : programming.tools
networking : yes
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
build      : |
    npm install
    ln -s node_modules/gulp/bin/gulp.js gulp
    ./gulp build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/yarn
    cp -R bin lib node_modules yarn.lock package.json $installdir/usr/lib/node_modules/yarn/
    ln -s /usr/lib/node_modules/yarn/bin/yarnpkg $installdir/usr/bin/yarn

